# GitHub Release configuration
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Performance Improvements
      labels:
        - performance
        - optimization
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Testing
      labels:
        - test
        - testing
    - title: Maintenance
      labels:
        - maintenance
        - chore
        - dependencies
    - title: Other Changes
      labels:
        - "*"