name: Auto-Approve PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    # Only run for the repository owner's PRs
    if: github.event.pull_request.user.login == github.repository_owner
    permissions:
      pull-requests: write
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Auto-approved by workflow for repository owner"